version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql_tea
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tea
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis_tea
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: tea_serveur
    restart: always
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: tea
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY}

      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend
    volumes:
      - ./storage:/workspace/storage
      - ./bootstrap/cache:/workspace/bootstrap/cache

volumes:
  db_data:
  redis_data:

networks:
  backend:
    external: true
    name: backend
    driver: bridge