FROM php:8.2-cli

# System deps + PHP extensions + Redis (phpredis)
RUN apt-get update && apt-get install -y \
    git zip unzip curl \
    libpng-dev libonig-dev libxml2-dev libzip-dev \
 && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd \
 && pecl install redis \
 && docker-php-ext-enable redis \
 && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /workspace